### ISSUE TITLE
version should be `2.0.0+1.docker18.09.3`?

### ISSUE THREAD

**Issue by julie-is-late** [kiendang/aur-nvidia-container-runtime-bin#1]
As much as I don't like that, it seems weird to have the src and bin versions of the packages on different versions, as it means `nvidia-docker` cannot pin it if needed. 

Thoughts?

**Comment by kiendang** [comment]
I noticed this too. Either we can change the version of this to `2.0.0+1.docker18.09.3` or use `provides=('nvidia-container-runtime=2.0.0+1.docker18.09.3')`?

**Comment by kiendang** [comment]
Thanks for all the cleaning up btw

**Comment by kiendang** [comment]
By pin you mean in case `nvidia-docker` requires a specific version of `nvidia-container-runtime`? Maybe I'm wrong but in that case even if the bin version is `2.0.0+1.docker18.09.3`, without `provides=('nvidia-container-runtime=2.0.0+1.docker18.09.3')` it wouldn't work.

So we have to decide on two separate things here
- whether to add version to `provides` for bin
- whether to add docker version to bin so bin and src have the same version

**Comment by julie-is-late** [comment]
I mean in case they do `depends=('nvidia-container-runtime=2.0.0+1.docker18.09.3')`, but after reading the pkgbuild wiki doc you're right that this can can be solved by adding the exact version to the `provides` array.

**Comment by kiendang** [comment]
Ok I'll add version to `provides` for all the bin packages. It's recommended in the doc anw.

**Comment by kiendang** [comment]
lol accidentially committed the built tar earlier@@ .gitignore updated 7b238de8794ff342ff35d5593dff9ee2dbf2a2ad
